FROM python:3.10-slim
#install packages
RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip && pip install mlflow psycopg2-binary boto3

# Set the working directory to /
WORKDIR mlflow_server
