# The builder image, used to build the virtual environment
FROM python:3.10-slim as builder

RUN pip install poetry

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /opt/app

COPY pyproject.toml poetry.lock README.md ./
# --no-root option instructs Poetry to avoid installing e2eML folder into the virtual environment.
RUN poetry install --only main --no-root && rm -rf $POETRY_CACHE_DIR

# syntax=docker/dockerfile:1.6
FROM python:3.10-slim
# Add repository code

ENV VIRTUAL_ENV=/opt/app/.venv \
    PATH="/opt/app/.venv/bin:$PATH"

COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

WORKDIR /opt/app
COPY e2eML/ e2eML/

CMD ["mlserver", "start", "/opt/app/e2eML/inference"]